twig:
    paths:
        '%kernel.project_dir%/vendor/revision-ten/forms/Resources/views': FORMS
    form_themes:
          - '@FORMS/Frontend/form_theme.html.twig'

framework:
    translator:
        paths:
            - '%kernel.project_dir%/vendor/revision-ten/forms/Resources/translations'

services:
    RevisionTen\Forms\Controller\FormController:
        autowire: true
        autoconfigure: true
    RevisionTen\Forms\Controller\TrackingController:
        autowire: true
        autoconfigure: true

    RevisionTen\Forms\Form\Items\EntityItem:
        autoconfigure: true
        autowire: true
        public: true
        tags: [form.type]

    RevisionTen\Forms\Services\FormService:
        autowire: true
        arguments:
            $config: '%forms%'

    RevisionTen\Forms\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        autowire: true
        autoconfigure: true

    # Command handlers.
    RevisionTen\Forms\Handler\FormCloneHandler:
        autowire: true
        public: true
